In [1]:
import os
import pandas as pd

In [2]:
#C:\Users\User\Documents\Atividades_andamento\Nayana

In [3]:
print(os.getcwd())
path_dir = r"C:\Users\User\Documents\Atividades_andamento\Nayana"
os.chdir(path_dir)
print(os.getcwd())

c:\Users\User\Documents\Atividades_andamento\Nayana
C:\Users\User\Documents\Atividades_andamento\Nayana

In [4]:
df = pd.read_excel('Fechamento_Tap_rev01.xlsx',skiprows=6, header=None)

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [ ]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,74
0,NaN,Depósitos de estéril,Depósito de Estéril E1,X,144,NaN,200,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
1,NaN,NaN,Depósito de Estéril E2,X,66,NaN,78,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
2,NaN,NaN,Depósito de Estéril E3,X,60,NaN,70,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
3,NaN,NaN,Depósito de Estéril E7/T5/E9,X,260,NaN,150,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
4,NaN,NaN,Depósito de Estéril E8,X,95,NaN,220,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
5,NaN,NaN,Depósito de Titânio T1,X,29,NaN,85,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
6,NaN,NaN,Depósito de Titânio T2,X,42,NaN,110,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
7,NaN,NaN,Depósito de Titânio T4,X,162,NaN,234,NaN,NaN,NaN,...,X,X,X,X,X,X,X,X,X,X
8,NaN,NaN,Depósito de Estéril E4,X,35.3,NaN,80,NaN,NaN,NaN,...,X,X,-,X,X,X,X,X,-,X
9,NaN,NaN,Depósito de Estéril E6,X,173.7,NaN,300,NaN,NaN,NaN,...,X,X,-,X,X,X,X,X,-,X

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
nomes = list(df.iloc[:,2].values)

type(nomes)

In [ ]:
nomes

['Depósito de Estéril E1',
 'Depósito de Estéril E2',
 'Depósito de Estéril E3',
 'Depósito de Estéril E7/T5/E9',
 'Depósito de Estéril E8',
 'Depósito de Titânio T1',
 'Depósito de Titânio T2',
 'Depósito de Titânio T4',
 'Depósito de Estéril E4',
 'Depósito de Estéril E6',
 'Depósito de Titânio T6',
 'Depósito de Estéril E11/Bigorna',
 'Planta de Britagem',
 'Planta de Beneficiamento',
 'Estação de bombeamento Mineroduto',
 'Planta Piloto',
 'Pátio de minério britado',
 'Pátios de resíduos',
 'Pátio de Ultrafinos',
 'Pátio de Apoio',
 'Barragem BR',
 'Barragem BL1',
 'Pilha de Magnetita',
 'PDR-I',
 'PDR-II',
 'PDM',
 'Barragem BD2',
 'Barragem BD5',
 'Barragem BA3',
 'Infraestrutura da Mina',
 'Galpões Geologia e Sondagem',
 'Metal AR',
 'Área de Britagem',
 'Infraestrutura da Usina',
 'Depósitos de Explosivos',
 'ORICA',
 'Áreas de Manutenção ',
 'Áreas de armazenagem de peças e resíduos',
 'Bombeamento Barragem',
 'Reservatórios de água e ETA',
 'Tratamento de Efluentes',
 'Subestação CG71',
 'Infraestrutura administrativa e escritórios',
 'Acessos e estacionamentos',
 'Barragem BRI',
 'Ponds Barragem BD2',
 'Pond Unidade de Beneficiamento',
 'Mineroduto',
 'Áreas desativadas e/ou removidas do Complexo',
 'Áreas Verdes Protegidas',
 'Áreas Verdes Não Protegidas',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [ ]:
barragens =[]
rows =[]
cont = -1
cajati =['Barragem B1', 'Barragem B2', 'Barragem B12']
itapira =['Barragem BR', 'Barragem BL-1', 'Barragem BD-2', 'Barragem BD-5', 'Barragem BA-3']
itapira =['Barragem BR', 'Barragem BL1', 'Barragem BD2', 'Barragem BD5', 'Barragem BA3']
for word in nomes:
    cont += 1
    try:
        if word in itapira:
            barragens.append(word)
            rows.append(cont)
    except:
        pass
print(barragens)
print(rows)

In [ ]:
df_filter = df.iloc[rows,:]
df_filter

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,74
20,NaN,Estruturas de disposição de rejeitos,Barragem BR,X,720,NaN,81,NaN,NaN,NaN,...,X,X,-,X,X,X,X,X,-,X
21,NaN,NaN,Barragem BL1,X,668,NaN,94,NaN,NaN,NaN,...,X,X,-,X,X,X,X,X,-,X
26,NaN,Depósitos de contenção de sedimentos,Barragem BD2,X,30,NaN,21,NaN,NaN,NaN,...,X,X,-,X,X,X,X,X,-,X
27,NaN,NaN,Barragem BD5,X,80,NaN,33,NaN,NaN,NaN,...,X,X,-,X,X,X,X,X,-,X
28,NaN,NaN,Barragem BA3,X,8,NaN,17,NaN,NaN,NaN,...,-,-,-,X,X,X,X,-,-,X

In [ ]:
df_filter.to_excel('tapira_filter.xlsx')

In [ ]:
files_ = ['Fechamento_Tap_rev01.xlsx','Fechamento_Ara_rev01.xlsx',
         'Fechamento_Cat_rev01.xlsx','Fechamento_Pat_rev01.xlsx',
         'Fechamento_Caj_rev01.xlsx'
         ]
print(files_)

tapira =['Barragem BR', 'Barragem BL1', 'Barragem BD2', 'Barragem BD5', 'Barragem BA3']
araxa = ['Barragem B1/B4', 'Barragem B5', 'Barragem B2','Barragem B6']
catalao =['Barragem de Magnetita', 'Barragem de Rejeitos BR']
patrocinio = ['Barragem de Lamas', 'Barragem de Lamas (cenário 1)']
cajati = ['Barragem B1', 'Barragem B2', 'Barragem B12']
set_ = [tapira,araxa,catalao,patrocinio,cajati]
set_name = []
k = -1
for file_ in files_:
  df = pd.read_excel(file_,skiprows=6, header=None)
  k += 1
  nomes = list(df.iloc[:,2].values)
  print(nomes)
  cont = -1
  barragens =[]
  rows =[]
  id_row = []
  id_k = 0
  for word in nomes:
    cont += 1
    try:
        if word in set_[k]:
          id_k += 1
          barragens.append(word)
          rows.append(cont)
          id_row.append(set_name[k]+str(id_k))
    except:
        pass
  print(barragens)
  print(rows)
  print(id_row)